language: python
python:
  - "3.5" # 3.5 development branch

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

services:
  - docker
# command to install dependencies

install:
  - docker-compose build

# command to run tests
script:
  - docker-compose run web python manage.py test