version: '2.0'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - uploads:/uploads
    depends_on:
      - web
  db:
    image: postgres
  web:
    build: .
    command: bash -c "python3 manage.py runworker & daphne -b 0.0.0.0 -p 80 PredoxWeb.asgi:channel_layer"
    volumes:
      - .:/code
      - uploads:/uploads
    expose:
      - "80"
    depends_on:
      - db
      - redis
  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    expose:
      - "6379"
volumes:
  uploads:
