# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.Project'),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Session'),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([('user', 'name')]),
        ),
    ]
