# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 18:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SOP', '0002_auto_20180406_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Company')),
                ('followers', models.ManyToManyField(blank=True, related_name='followed_project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('N', 'Not started'), ('I', 'In progress'), ('C', 'Complete')], default='N', max_length=1)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project_management.Project')),
                ('related_experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Experiment')),
                ('sop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SOP.SOP')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('project', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('company', 'name')]),
        ),
    ]
