# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0005_auto_20180130_2119'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('project', 'name')]),
        ),
    ]
