# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 21:40
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=255)),
                ('reactor_diameter', models.FloatField(verbose_name='Reactor Diameter [inch]')),
                ('reactor_length', models.FloatField(verbose_name='Reactor Length [inch]')),
                ('num_chambers', models.IntegerField(verbose_name='# Chambers')),
                ('date', models.DateField(verbose_name='Date (d/m/y)')),
                ('removal_target', models.CharField(max_length=255, verbose_name='Removal Target')),
                ('reactor_age', models.FloatField(verbose_name='Age of Reactor')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experimentData', django.contrib.postgres.fields.jsonb.JSONField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='scientist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Scientist'),
        ),
    ]
