# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('app', '0002_auto_20180105_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('company', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together=set([('company', 'name')]),
        ),
    ]
