# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_experiment_scientist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='person',
        ),
        migrations.AlterField(
            model_name='experiment',
            name='num_chambers',
            field=models.IntegerField(default=0, verbose_name='# Chambers'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='reactor_age',
            field=models.FloatField(default=0, verbose_name='Age of Reactor'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='reactor_diameter',
            field=models.FloatField(default=0, verbose_name='Reactor Diameter [inch]'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='reactor_length',
            field=models.FloatField(default=0, verbose_name='Reactor Length [inch]'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='removal_target',
            field=models.CharField(default=0, max_length=255, verbose_name='Removal Target'),
        ),
    ]
