# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-06 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171206_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='metadata_template',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
