# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180126_2317'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='notification',
            managers=[
            ],
        ),
    ]
