# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171206_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='company',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='group',
        ),
        migrations.RemoveField(
            model_name='project',
            name='metadata_template',
        ),
        migrations.AddField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='edit_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fields',
            name='data_type',
            field=models.CharField(choices=[('INT', 'Integer'), ('FLOAT', 'Decimal'), ('DATE', 'Date'), ('STRING', 'Text')], default='STRING', max_length=6),
        ),
        migrations.AddField(
            model_name='project',
            name='extra_metadata_fields',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
