# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170919_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fields', models.ManyToManyField(to='app.Fields')),
            ],
        ),
        migrations.RemoveField(
            model_name='scientist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Scientist',
        ),
    ]
