# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 18:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20180123_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchedexperiment',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='watchedexperiment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchedprojects',
            name='project',
        ),
        migrations.RemoveField(
            model_name='watchedprojects',
            name='user',
        ),
        migrations.AddField(
            model_name='experiment',
            name='followers',
            field=models.ManyToManyField(related_name='followed_experiments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifications',
            name='action',
            field=models.CharField(choices=[('EXP', 'Watched Experiment Updated'), ('PRJ', 'Experiment added to watched project'), ('COM', 'Comment added to watched experiment')], default='EXP', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='content',
            field=models.CharField(default='x', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='from_usr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_usr', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='title',
            field=models.CharField(default='x', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='followers',
            field=models.ManyToManyField(related_name='followed_project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='WatchedExperiment',
        ),
        migrations.DeleteModel(
            name='WatchedProjects',
        ),
    ]
