# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SOP', '0003_auto_20180305_2321'),
        ('app', '0003_experiment_sop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='sop',
        ),
        migrations.AddField(
            model_name='experiment',
            name='sop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SOP.SOP'),
        ),
    ]
