# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171211_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fields',
            options={'verbose_name_plural': 'fields'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='extra_metadata_fields',
        ),
    ]
