# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180127_0025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
