# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 18:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20180124_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate', models.CharField(choices=[('COM', 'commented on'), ('PROJ', 'uploaded a new experimentto'), ('UPL', 'updated experiment')], max_length=50)),
                ('object_type', models.CharField(max_length=50)),
                ('object_pk', models.IntegerField()),
                ('content', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipients', models.ManyToManyField(related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='from_usr',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
