# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171212_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='fields',
            name='empty',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
