# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171002_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Group'),
        ),
    ]
