# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171002_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimenttag',
            name='exp_id',
        ),
        migrations.RemoveField(
            model_name='experimenttag',
            name='tag_id',
        ),
        migrations.DeleteModel(
            name='ExperimentTag',
        ),
    ]
