# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180125_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='object_type',
            field=models.CharField(choices=[('EXP', 'experiment'), ('PRJ', 'project')], max_length=3),
        ),
    ]
