# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180125_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='object_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='predicate',
            field=models.CharField(choices=[('COM', 'commented on'), ('PRJ', 'uploaded a new experiment to'), ('UPD', 'updated experiment')], max_length=3),
        ),
    ]
