# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_experiment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='friendly_name',
            field=models.CharField(max_length=255),
        ),
    ]
