# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 18:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentmetadata',
            name='experiment',
        ),
        migrations.AddField(
            model_name='experiment',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
        migrations.DeleteModel(
            name='ExperimentMetaData',
        ),
    ]
