# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_company_settings'),
        ('app', '0010_auto_20171222_1810'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fields',
            unique_together=set([('company', 'name')]),
        ),
    ]
