# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_experiment_friendly_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experimentdata',
            options={'verbose_name_plural': 'experiment data'},
        ),
    ]
