# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20171030_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='num_chambers',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='reactor_age',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='reactor_diameter',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='reactor_length',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='removal_target',
        ),
    ]
