# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_tutorial',
            field=models.BooleanField(default=True),
        ),
    ]
