# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180112_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissiongroupcompany',
            name='company',
        ),
        migrations.RemoveField(
            model_name='permissiongroupcompany',
            name='group',
        ),
        migrations.DeleteModel(
            name='PermissionGroupCompany',
        ),
    ]
